fos_comment:
    db_driver: orm
    class:
        model:
            comment: App\Entity\Comment
            thread: App\Entity\Thread
            vote: App\Entity\Vote     
    form:
        comment:
            type: App\Form\CommentType
twig:
    date:
        format: d-m-Y H:i:s